"""Generate a markdown digest from clusters."""
from __future__ import annotations

from .types import Digest


def render_markdown(d: Digest) -> str:
    """Render a Digest as a markdown report."""
    lines = [
        "# Customer Discovery Digest",
        "",
        f"*Generated: {d.generated_at.isoformat()}*",
        f"*Window: last {d.window_hours}h · Sources: {', '.join(d.sources)}*",
        f"*Pain points scanned: **{d.n_pain_points}** · Clusters: **{len(d.clusters)}***",
        "",
        "## Top themes",
        "",
    ]
    if not d.clusters:
        lines.append("*(no pain points matched the keyword filters in this window)*")
    else:
        for c in d.clusters:
            lines.extend([
                f"### {c.summary}",
                "",
                f"**{c.n_posts} posts · avg score {c.avg_score}**",
                "",
                f"> {c.representative_quote}",
                "",
                "Sample posts:",
                "",
            ])
            for u in c.sample_urls:
                lines.append(f"- {u}")
            lines.append("")
    lines.extend([
        "---",
        "*Generated by [customer-discovery-agent]"
        "(https://github.com/alex-jb/customer-discovery-agent)*",
    ])
    return "\n".join(lines)
